### ISSUE TITLE
즐겨찾기 버튼

### ISSUE THREAD

**Issue by sleepylion99** [kyechan99/chzzk-plus#13]
즐겨 찾기 버튼 한번 누르고 두번 눌려도 즐겨 찾기 패널에서 반응을 안합니다

버전은 1.0.7 입니다

**Comment by kyechan99** [comment]
안녕하세요~
즐겨찾기 기능은 즐겨찾기 이후 새로고침을 해야 패널에서 변경됩니다.
혹시 새로고침을 했음에도 반응이 없을까요?

**Comment by sleepylion99** [comment]
네 반응이 없었어요

**Comment by sleepylion99** [comment]
다시 확인 해보니 반응이 있네요.  그 혹시 색 들어간 즐겨찾기 버튼 이면 즐겨찾기 이고 색 빠진 즐겨찾기 버튼이면 즐겨찾기 해제 상태인걸로 변경 해주시면 안될까요?

**Comment by kyechan99** [comment]
색상 변경은 기존 사용자분들에게 혼란을 줄 수 있어서요.

즐겨찾기 중인 상태인 경우 `즐찾중` 인 상태로 변경했습니다.
