### ISSUE TITLE
1월 5일 업데이트 이후 버튼 추가가 안 됩니다

### ISSUE THREAD

**Issue by RUM1CUB3** [kyechan99/chzzk-plus#14]
문제 생겨서 프로그램 삭제 후 다시 재설치 했는데 업데이트랑 겹쳐서 그런지 전과 달리 녹화 프로그램을 포함해서 어떤 기능도 사이트에서 보이지 않습니다

**Comment by kyechan99** [comment]
안녕하세요 :)
수정한 버전(v1.0.8)을 스토어에 막 업로드 했습니다.
적용되기까지 약 하루정도 걸립니다.
제보해주셔서 감사드립니다 ~!
