### ISSUE TITLE
치지직 글씨 크기 안바뀝니다

### ISSUE THREAD

**Issue by kth1256** [kyechan99/chzzk-plus#15]
치지직 글씨 17 로 맟췃는데 다른걸로 바꿔도 예전 초기 크기로 그대로입니다

**Comment by kyechan99** [comment]
안녕하세요 :)
수정한 버전(v1.0.8)을 스토어에 막 업로드 했습니다.
적용되기까지 약 하루정도 걸립니다.
제보해주셔서 감사드립니다 ~!
