### ISSUE TITLE
트위치처럼 채팅창 다향한컬러

### ISSUE THREAD

**Issue by glrllslsz** [kyechan99/chzzk-plus#2]
트위치처럼 채팅창 다향한컬러로 나오게 부탁드려요!

**Comment by kyechan99** [comment]
안녕하세요 ~ 😄 
재밌는 아이디어네요. 한번 시도해보겠습니다

**Comment by glrllslsz** [comment]
치즈 채팅 제거

m : 음소거/음소거 취소

t : 넓은 화면(트위치 극장모드)/취소

f : 전체화면/취소

트위치 프리뷰처럼 

뒤로돌리기 기능 

이런것들도 가능할까요?

**Comment by kyechan99** [comment]
말씀하신 치즈 채팅 제거나 키보드 기능들은 고려해 두겠습니다. 👍 
일단 다양한 컬러 기능이 추가되어 해당 이슈는 닫습니다.
(설정창에 '테마' 모드로 변경하세요.)
