### ISSUE TITLE
[버그] 채팅 크기 조절시 스크롤 쌓임

### ISSUE THREAD

**Issue by Lsh2375000** [kyechan99/chzzk-plus#27]
### **버그 내용**

채팅크기를 20으로 조절하고 새로고침하니까 채팅이 올라오다가 멈추고 밑에 계속 쌓입니다.
다시 새로고침 해도 그대로 발생합니다.
![스크린샷 2024-01-20 010659](https://github.com/kyechan99/chzzk-plus/assets/146049531/0a6e371c-3701-4fb1-a6d4-49ba6cffad38)

### **환경**

version: v1.0.10
os: 윈도우11
browser: 크롬

**Comment by Lsh2375000** [comment]
다시 원래 크기로 돌리면 정상적으로 채팅 올라오긴 합니다

**Comment by kyechan99** [comment]
치지직내에 채팅 스크롤 인식을 바꾸면서 일어난 일로 파악하고 있으며 저도 인지하고 있던 상태였습니다만
최근 또 해당 인식을 변경한 것으로 보입니다.

만약 제보자분께서 아직도 그러한 현상을 겪고 계시거나 해당 이슈가 재발시 다시 현 제보를 open 하도록 하겠습니다.
