### ISSUE TITLE
혹시 채팅색상 관련은 제거 못하나요?

### ISSUE THREAD

**Issue by jangforce08** [kyechan99/chzzk-plus#3]
다른 확장 프로그램 스크립트를 같이 쓰고 있는데 pip때문에 쓰고 싶은데 해당 프로그램 사용시 기존 스크립트가 작동을 안하네요

**Comment by jangforce08** [comment]
방법만 대충이라도 알려주시면 구글링 해보면서 pip 기능만 추출하고 싶은데

**Comment by kyechan99** [comment]
안녕하세요 😄 
사용하시는 다른 확장 프로그램과 스크립트가 어떤 것일까요?
어떤 부분에서 작동이 안하는지 좀 더 알아야 할 것 같아요.

**Comment by jangforce08** [comment]
> 안녕하세요 😄 사용하시는 다른 확장 프로그램과 스크립트가 어떤 것일까요? 어떤 부분에서 작동이 안하는지 좀 더 알아야 할 것 같아요.

https://www.fmkorea.com/6523427754
여기에 있는 스크립트입니다. kye님의 스크립트는 시청자 전원을 모두 동일한 색상으로 바꾸는 코드이고
링크의 코드는 트위치 처럼 랜덤한 색상을 입히는 코드입니다

**Comment by kyechan99** [comment]
이해했습니다.
생각보다 이름 색상이 다채로운걸 선호하시는 분이 많이 계신 것 같네요.
사용하시는 스크립트처럼 이름 색상을 다양하게 사용하는 기능도 추가하면서 기존의 동일 색상 기능도 ON/OFF 가능한 형태로 제공하면 더 편하실 듯 싶네요.

**Comment by jangforce08** [comment]
추가로 pip 기능이 다시보기에는 작동을 하지 않는데 이것도 지원 가능한가요

**Comment by kyechan99** [comment]
추가되어 해당 이슈는 닫습니다.
