### ISSUE TITLE
[버그] 방제가 길어지면 그 우측의 즐찾버튼 등 글자가 겹쳐보임

### ISSUE THREAD

**Issue by codebravosix** [kyechan99/chzzk-plus#30]
### **버그 내용**

스트리머가 방제를 길게 설정했고 방제는 줄바꿈되어 아랫줄까지  방제가 넘어갔고 버튼의 텍스트가 겹치거나 잘려 보입니다.

![123](https://github.com/kyechan99/chzzk-plus/assets/157794290/16be9efe-25c0-4e69-92bb-7436255c71de)

### **환경**

version: 1.0.10
os: W10
browser: 크롬 

치즈 나이프와 같이 사용하며 기능이 안겹치도록 나름대로 기능 끄고 켬.

### **기타** 

비전문가라 대안은 모르겠고 버튼의 위치는 편하고 좋습니다(화면 우하단)

**Comment by kyechan99** [comment]
v1.0.11 버전때 수정하여 업로드 했습니다~!
제보 감사드립니다
