### ISSUE TITLE
[버그]음소거 버튼 및 넓은화면 버튼작동안해요

### ISSUE THREAD

**Issue by persiese** [kyechan99/chzzk-plus#31]
### **버그 내용**

키 이벤트중 음소거 버튼과 넓은화면 버튼은 작동이 안되는 상태입니다

넓은화면 버튼을 사용하면 팔로우목록쪽이 새로고침되고 음소거버튼은 작동이 안됩니다.

### **환경**

version: v1.0.10
os: windows10
browser: edge

**Comment by kyechan99** [comment]
안녕하세요~!
최근 치지직 자체적으로 해당 기능을 지원하게 되어 중복 이벤트 발생으로 일어난 버그로 보입니다.
해당 기능을 '사용하지 않음'으로 설정함으로써 해결하실 수 있을 것 같습니다.

chzzk-plus v1.0.11 부터는 해당 기능을 더 이상 지원하지 않습니다.
제보 감사드립니다 :)
