### ISSUE TITLE
[버그] 기본화면에서 녹화 버튼 누르고 넓은화면으로 전환시 녹화 버튼이 초기화 됨

### ISSUE THREAD

**Issue by ehdrms3825** [kyechan99/chzzk-plus#33]
### **버그 내용**

기본화면에서 녹화 버튼을 클릭하고
넓은화면으로 전환시 녹화버튼이 초기화되어 '녹화중' 에서 '녹화' 로 저절로 바뀌게 됩니다.
때문에 이전의 녹화 버튼으로 녹화중인 영상은 녹화종료를 할 수 없게되고
방송이 종료될 시에 녹화 버튼을 누른 횟수만큼의 영상이 일괄로 다운받아 지게 되며,
넓은화면으로 전환 이후의 소리는 녹음되지 않은채 저장되게 됩니다.

![ezgif-5-49e59841f6](https://github.com/kyechan99/chzzk-plus/assets/68108825/992999bc-184c-45b4-af82-1d574f103f6a)

### **환경**
version: v1.0.11
os: windows 11 home edition
browser: chrome

**Comment by kyechan99** [comment]
`v1.3.0` 에서 녹화 기능을 동영상 플레이어 기준으로 이동했습니다.
