### ISSUE TITLE
[기능 제안] 각종 기능에 단축키를 추가해주세요

### ISSUE THREAD

**Issue by liltada** [kyechan99/chzzk-plus#34]
### **제안**
캡처 저장 및 빨리 감기 기능에 단축키를 추가해주세요
캡처 저장 단축키 예시로 트위치에서 사용하던 확장 프로그램 링크를 첨부합니다
https://chromewebstore.google.com/detail/%E3%82%B9%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%9C%E3%82%BF%E3%83%B3/ahajpggnfmlmabdkmgijlkgoajjgkiln

**Comment by kyechan99** [comment]
v1.0.12 버전 부터  스크린샷, 영상 배속의 단축키가 추가되었습니다.
감사합니다.
