### ISSUE TITLE
[기능 제안] 블라인드 챗 표시

### ISSUE THREAD

**Issue by ffxivvillein** [kyechan99/chzzk-plus#37]
### **제안**

블라인드 처리 된 채팅의 내용을 지우지 않고 취소선이나 블러처리하여 확인할 수 있는 기능 요청합니다.

**Comment by kyechan99** [comment]
안녕하세요.
블라인드 채팅 내용의 경우 채팅 문자 자체가 화면에 나타나기 이전에 변경되어 전송됩니다.
채팅 내용을 취소선 or 블러처리 자체는 네이버 측에서 직접 관여해야 할 내용으로 보입니다.

v1.1.1 버전에서 블라인드 되어야할 메세지를 기존 치즈 제거 기능과 동일하게 완전 제거 될 수 있도록 추가하였으니 이 기능이 도움 되었음 합니다. 
감사합니다.
