### ISSUE TITLE
[버그] 중복코드

### ISSUE THREAD

**Issue by Shihyeon** [kyechan99/chzzk-plus#40]
### **버그 내용**

https://github.com/kyechan99/chzzk-plus/blob/a4263995d633287ddccfbf44d8521ad7b5e9a29a/src/App.tsx#L48C1-L48C50

### **환경**

version: v1.0.12
os: 
browser:

**Comment by kyechan99** [comment]
안녕하세요 :)
꽤나 예전에 작성한 내용인데 그동안 발견을 못했던게 놀랍네요..ㅎㅎ
제보 감사드립니다.
