### ISSUE TITLE
[버그] 생방송 새로고침 기능에 생방송 체크와 동시에 추가로 고려해야 할 값이 있는 것 같습니다.

### ISSUE THREAD

**Issue by yhunl123** [kyechan99/chzzk-plus#42]
### **버그 내용**

생방송이 시작될 때 브라우저에 비디오 플레이어 태그는 생기는데 
간헐적으로 이 video 태그에 src가 입력이 안되는 경우가 있습니다.

치지직 자체의 문제로 보이며
발생하는 조건은 추측이긴 하지만 방송 시작 플래그는 변했지만 방송 영상 url이 발급되지 않은 경우
같습니다.

이 경우에 플레이어는 뜨지만
'알수없는 오류가 발생했습니다.'
라는 문구가 뜨며 다시 새로고침 되지 않는 문제가 발생하게 됩니다.

### **환경**

version: 1.1.0
os: windows 10
browser: 네이버 웨일

### **기타**

따라서 해당 태그의 존재유무만 체크하는 것이 아닌 해당 태그의 src값이 정상적으로 들어있는지 까지 확인을 해야 할 것 같습니다.

![image](https://github.com/kyechan99/chzzk-plus/assets/84111407/b26aae80-7bb8-4536-88e7-861b26a19a03)
오류 발생 시 video 태그 속성 값

![image](https://github.com/kyechan99/chzzk-plus/assets/84111407/be9f93df-deb8-438c-a8db-ad42db569b9c)
정상 작동 중 video 태그 속성 값

**Comment by kyechan99** [comment]
수정하여 `v1.1.1` 에 적용하였습니다.
만약 버그 재발시 reopen 하겠습니다.
감사합니다.
