### ISSUE TITLE
[기능 제안] 스트리머 완전 차단 기능

### ISSUE THREAD

**Issue by lunamoth** [kyechan99/chzzk-plus#43]
### **제안**

특정 스트리머를 완전히 차단할 수 있는 기능 추가 부탁드립니다.

치지직 자체 차단 기능을 쓰면, 전체 리스트에 차단된 스트리머 입니다 라고 보입니다.

이렇게 메시지 나오지 않고 완전히 차단 할 수 있으면 좋을것 같습니다.

**Comment by kyechan99** [comment]
안녕하세요.

제안해주신 기능을 추가하였습니다.

해당 기능은 `v1.1.2` 버전부터 적용됩니다.
현재 `v1.1.1` 버전을 막 업로드 한 상태라 다음 주 (~3/22) 내로 업데이트 될 예정입니다.

현 이슈는 적용된 버전(v1.1.2) 게시 후에 닫도록 하겠습니다.

감사합니다.
