### ISSUE TITLE
[기능 제안] 팔로우 채널 항상 펼치기

### ISSUE THREAD

**Issue by shs14kor** [kyechan99/chzzk-plus#44]
### **제안**

팔로우 채널이 활성화 된 방송이 5개 밖에 나오지 않습니다.
즐겨찾기를 해도 즐겨찾기와 팔로우 채널 합쳐서 5개밖에 나오지 않습니다.
나오게 하려면 메뉴 확장을 누르고 더 보기를 눌러야 나옵니다.
그런데 다시 새로 고침을 하거나 다른 방으로 이동하면 다시 5개 밖에 안나옵니다.
저는 브라우저를 전체 화면으로 하지 않고 화면 해상도를 작게 해서 보는데 그것 때문인거 같은데
화면 해상도 작게 해도 팔로우 채널 전체 나오게 해주세요.

**Comment by kyechan99** [comment]
안녕하세요. 
정확히 어떤 상황인지 정보가 더 필요합니다.
현재 치치직 플러스는 페이지 로드시 '팔로우 채널 더보기' 를 자동 활성화 하는 기능이 탑재되어있습니다.
