### ISSUE TITLE
[기능 제안] 단축키 설정 및 끄기 기능 필요

### ISSUE THREAD

**Issue by MINFirz** [kyechan99/chzzk-plus#45]
### **제안**

단축키 설정을 본인이 직접 할수 있도록 하거나, 
해당기능을 끄거나 킬수 있도록 부탁드립니다...

듀얼모니터를 키고있어 게임과 방송을 같이 보고있을때 치지직창이 활성화가 되어있는걸 까먹어 
'S ' 버튼을 누르면 방송스크린샷이 다운받아져서 사용하기 매우 껄끄럽습니다.

**Comment by Mochaccino99** [comment]
ㄹㅇ 비디오 스피드 컨트롤러랑 키겹쳐서 스샷 마구마구 눌림
