### ISSUE TITLE
[기능 제안]광고 자동 건너뛰기

### ISSUE THREAD

**Issue by premiuser** [kyechan99/chzzk-plus#49]
광고 자동 건너뛰기 있었으면 좋겠어요
광고 건너뛰기 누르는데 귀찮은 경우가 좀 있기도 하고
광고 떴는데 pip 모드면 좀 귀찮아짐

**Comment by kyechan99** [comment]
광고와 같은 민감한 사항은 다루지 않습니다.
감사합니다.
