### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by thukuni** [kyechan99/chzzk-plus#5]
1.  "화면 클릭시 일시정지 방지" 기능 삭제 필요
 - 치지직이 업데이트 되면서 화면을 클릭해도 일시정지가 되지 않음
 - 오히려 현재  Chzzk Plus를 깔면 더블 클릭으로 전체화면 되는 현재 기능이 오작동함

2. 문구 수정
 - "채팅 이름 생상": 설명과 실제 기능을 보면 , '테마'모드에서 작동 -> '커스텀'모드에서 작동 으로 변경되어야 할 것 으로 보임
 
3. 키보드 단축키  적용 여부?
 - 업데이트 내용상에는 있는데 현재 키보드 단축키가 제대로 동작 하지 않는 것으로 보임 
 - "M" - Mute 필요..

**Comment by kyechan99** [comment]
안녕하세요 :)

2번의 경우는 확실히 잘못 작성한게 맞네요 !  
다음 버전에 수정해서 업로드 하겠습니다.

1 번의 경우는 저도 최근에 발견하여 변경될 예정입니다.

3 번의 경우는 혹시 활성화 시킨 것이 맞으실까요?
어떤 버전을 사용하고 계시는지 알려주세요.  
제 환경에선 당장 버그가 나타나지 않아서요. Mute 기능도 존재합니다.
만약 채팅창이나 검색창 등에 이벤트가 활성화 되어있다면 작동하지 않는 것이 맞습니다.

**Comment by thukuni** [comment]
우선, Chzzk Plus 잘 쓰고 있습니다.  감사합니다.

3번 답변입니다.
방금 기존 버전 삭제하고 v1.0.1 최신 버전 다시 설치했어요~
별도로 단축키 활성화 하는 옵션이 따로 있나요?

**Comment by kyechan99** [comment]
ㅎㅎ !
문서에 작성하는 바람에 오해를 불러일으킨 것 같네요.
아직 1.0.1 버전에는 단축키 옵션이 없어요.

[크롬 마켓](https://chromewebstore.google.com/detail/chzzk-plus/miampiopgfpnimmggagljgbpmjmjdjia?hl=ko&utm_source=ext_sidebar)에 버전을 변경하려면 검증의 절차가 있어서 패치 변경까지는 시간이 조금 걸려요.

시간이 지나면 업데이트 되어 옵션에 추가 될 겁니다!
(아마 내일쯤 단축키 기능 등이 추가된 1.0.2 로 자동 업데이트 될 거에요)
