### ISSUE TITLE
[기능 제안] 다시보기 녹화

### ISSUE THREAD

**Issue by chokobee** [kyechan99/chzzk-plus#52]
잘 사용했던 다시보기 녹화가 없어졌네요.

가능하시면 복구를 부탁드리고 싶습니다.

항상 잘 사용하고 있습니다. 

감사합니다. 건강하세요.

**Comment by kyechan99** [comment]
`v1.3.2` 에 오디오 압축, 녹화, 캡처 기능이 다시 복구 됩니다.
감사합니다.
