### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by zephyros06** [kyechan99/chzzk-plus#59]
치지직 로그인이 안됨 모바일은 가능

**Comment by zephyros06** [comment]
네이버 계정으로 로그인이 안됨

**Comment by kyechan99** [comment]
안녕하세요. 본 확장프로그램은 로그인 경로 `nid.naver.com` 에 접근하지 않습니다.
따라서 제보해주신 로그인 기능 관련 행동을 취하실 때에는 확장 프로그램이 작동하지 않아 어떠한 영향도 드리고 있지 않습니다.

다른 프로그램과 충돌하고 있는지 확인해주시길 바라며,
현 확장프로그램을 OFF 하였을때에도 동일 현상이 발생하신다면 더 자세한 상황에 대해 다시 제보해 주시면 감사드리겠습니다.
