### ISSUE TITLE
[버그] Chrome 130+ 버전에서 CRXJS를 사용하는 확장 프로그램이 제대로 동작하지 않는 문제

### ISSUE THREAD

**Issue by Deepbluewarn** [kyechan99/chzzk-plus#61]
### **버그 내용**

https://github.com/crxjs/chrome-extension-tools/issues/918#issuecomment-2417036333
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Nr3QNKFv74c/m/PYLvA7dOAAAJ?pli=1

web_accessible_resources의 use_dynamic_url 속성을 제거하거나 false로 설정해야 한다고 합니다.

![error](https://github.com/user-attachments/assets/6a23c750-66e9-4dfa-b8d8-98c5cb753ddb)

### **환경**

version: 1.3.4
os: windows
browser: chrome 130.0.6723.59

**Comment by kyechan99** [comment]
안녕하세요!
제보와 정보 정말 감사드립니다 😄 
빠른 시일내에 확인하여 작업토록 하겠습니다.

**Comment by khk4912** [comment]
https://github.com/crxjs/chrome-extension-tools/releases/tag/%40crxjs/vite-plugin%402.0.0-beta.26

해당 문제 수정된 버전이 배포되어 crxjs 버전 업으로 해결될 것 같습니다!

**Comment by kyechan99** [comment]
crxjs 버전 업으로 v1.3.5 업데이트 해두었습니다.
감사드립니다.
