### ISSUE TITLE
캡쳐기능 사용 후 canvas element 삭제 필요

### ISSUE THREAD

**Issue by SnorlaxH** [kyechan99/chzzk-plus#7]
![image](https://github.com/kyechan99/chzzk-plus/assets/13658586/1bfc1849-2169-448a-a641-f1fd7ae0086f)
캡쳐기능 사용 후 canvas가 그대로 남아서 화면이 이상하게 보입니다.

**Comment by kyechan99** [comment]
감사합니다 ~ !
수정된 버전(v1.0.4)을 업로드 했으니 적용 될 때까지만 기다려주세요!
