### ISSUE TITLE
넓은 화면 -> 기본 화면 가면 확장프로그램 작동 안하는 버그

### ISSUE THREAD

**Issue by sleepylion99** [kyechan99/chzzk-plus#8]
브라우저는 네이버 웨일 3.23.214.17 이고 윈도우 11 입니다

치지직 기본 화면에서 녹음 버튼 눌려 시작 하였고 넓은 화면으로 보다가

넓은 화면을 해제를 하니 즐겨찾기 패널, 즐겨찾기, 캡쳐, 녹화 버튼이 사라지고 팔로우 채널 에서 방속제목 및 미리보기 썸네일 볼수 없는 버그을 발견 하였습니다

새로고침을 하면 다시 생기긴 합니다

아 확장 프로그램 버전은 1.0.4 입니다

**Comment by sleepylion99** [comment]
아 확장 프로그램 버전은 1.0.3 입니다

**Comment by kyechan99** [comment]
안녕하세요 :)
방금 막 수정된 `v1.0.5` 를 업로드 했습니다.
아마 내일 중으로 적용될 거에요.

만약 재발한다면 다시 오픈해주시면 감사드리겠습니다.
